#!/usr/bin/env python3
"""
Self-host the text fonts (Outfit, Space Grotesk, Mr Dafoe, Patrick Hand).

Why: loading them from fonts.googleapis.com adds two render-blocking
third-party round-trips (CSS on googleapis + woff2 on gstatic). Self-hosting
serves them from our own origin with immutable caching and lets us preload the
critical ones. We copy Google's exact woff2 files and unicode-ranges, so
rendering is byte-for-byte identical (including French glyphs like œ).

Re-run only if the font selection changes. Usage:
    python scripts/build-text-fonts.py

Outputs: public/fonts/*.woff2  +  src/styles/fonts.css
"""
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONTS_DIR = ROOT / "public" / "fonts"
CSS_OUT = ROOT / "src" / "styles" / "fonts.css"
# Same families/weights the site already used.
CSS_URL = ("https://fonts.googleapis.com/css2?"
           "family=Mr+Dafoe"
           "&family=Outfit:wght@300;400;600;800"
           "&family=Space+Grotesk:wght@300;500;700;900"
           "&family=Patrick+Hand&display=swap")
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req) as r:
        return r.read()


def slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def main() -> None:
    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    css = get(CSS_URL).decode()

    # Each @font-face is preceded by a /* subset */ comment.
    blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})",
                        css, re.S)
    out_lines = [
        "/* Self-hosted text fonts — generated by scripts/build-text-fonts.py.",
        "   Do not edit by hand; re-run the script to regenerate. */",
        "",
    ]
    downloaded = 0
    for subset, block in blocks:
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
        style = re.search(r"font-style:\s*(\w+)", block).group(1)
        urange = re.search(r"unicode-range:\s*([^;]+);", block).group(1).strip()
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)

        suffix = "i" if style == "italic" else ""
        fname = f"{slug(family)}-{weight}{suffix}-{subset}.woff2"
        (FONTS_DIR / fname).write_bytes(get(url))
        downloaded += 1

        out_lines += [
            f"/* {family} {weight} {style} — {subset} */",
            "@font-face {",
            f"  font-family: '{family}';",
            f"  font-style: {style};",
            f"  font-weight: {weight};",
            "  font-display: swap;",
            f"  src: url('/fonts/{fname}') format('woff2');",
            f"  unicode-range: {urange};",
            "}",
            "",
        ]

    CSS_OUT.write_text("\n".join(out_lines))
    print(f"Downloaded {downloaded} woff2 files to {FONTS_DIR.relative_to(ROOT)}")
    print(f"Wrote {CSS_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
